# Generated by Django 3.2.6 on 2021-08-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i1', models.TextField()),
                ('i2', models.TextField()),
                ('i3', models.TextField()),
                ('i4', models.TextField()),
                ('i5', models.TextField()),
                ('i6', models.TextField()),
                ('i7', models.TextField()),
                ('i8', models.TextField()),
                ('updated', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
