# Generated by Django 3.2.6 on 2021-08-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='body',
            field=models.TextField(default='Cur NUll'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='updated',
            field=models.TextField(default='00:00'),
        ),
    ]
