# Generated by Django 3.2.6 on 2021-08-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210819_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='body',
            field=models.TextField(default='Cur Null'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='updated',
            field=models.TextField(default='0000'),
        ),
    ]
