# Generated by Django 3.2.6 on 2021-08-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210819_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='body',
            field=models.TextField(blank=True, default='Cur Null'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='updated',
            field=models.TextField(blank=True, default='0000'),
        ),
    ]
