# Generated by Django 3.2.6 on 2021-08-18 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210819_0018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-created']},
        ),
    ]
