# Generated by Django 3.1.2 on 2021-08-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210819_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='eta',
            field=models.TextField(blank=True, default='Cur Null'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
